### ISSUE TITLE
Mention the PyKE website

### ISSUE THREAD

**Issue by barentsen** [mirca/aas_poster#3]
Let's add a link to `pyke.keplerscience.org` and/or the GitHub repo to the poster!

**Comment by barentsen** [comment]
@mirca I looked at the poster again just now.  It looks fantastic!!  Just don't forget to add a link to PyKE, and if you have time, add a Kepler or K2 logo to make it extra spiffy!

**Comment by mirca** [comment]
done! I'm trying to make the Kepler and K2 logo work in LaTeX

**Comment by barentsen** [comment]
Great!!   Please send whatever version you have around 10am or so to Mark/Wendy so they can do the test print.  (Doesn't have to be the final version.)
