### ISSUE TITLE
Celebrate

### ISSUE THREAD

**Issue by barentsen** [mirca/aas_poster#4]
Congratulations to @mirca on his first AAS poster.  You can close this issue once you have celebrated this milestone!

**Comment by mirca** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by mirca** [comment]
@barentsen I'm closing this after this awesome weekend! xD

**Comment by barentsen** [comment]
:+1: Celebration very well executed =)
